### ISSUE TITLE
How do I make the bold message in a custom color?

### ISSUE THREAD

**Issue by vinnyg0621** [miraisoft-de/mc-forge-loginmessages#11]

**Comment by miraisoft-de** [comment]
There are several Minecraft color codes/formats. You can combine them as you like. Use the internet search engine of your choice. Please consider that this page is for mod issues.

**Comment by miraisoft-de** [comment]
There is a command example on the mod description page:
`/loginmessage add <<c>>Red text`
leads to red text.

**Comment by vinnyg0621** [comment]
i tried doing /loginmessage add <<l>> <<2>> [MESSAGE] but it removed the bold.

**Comment by vinnyg0621** [comment]
and i asked how to make the message in both bold _and_ a color.
